upload:
  path: /home/avada/web/slj.demodev.cc/projects/My-house24_Rudiuk_Lesyk/uploads

aws:
  accessKey: ${awsAccessKey}
  secretAccessKey: ${awsSecretAccessKey}
  endpoint: https://testbucket-my-house.s3.us-east-2.amazonaws.com/
  bucketName: testbucket-my-house

spring:
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/my_house24
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /my-house24-rudiuk-lesyk
  error:
    whitelabel:
      enabled: false