name: Build Docker image

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Add secret to admin
        env:
          awsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sendgridSecretKey: ${{ secrets.SENDGRID_SECRET_KEY }}
          sendgridSender: ${{ secrets.SENDGRID_SENDER }}
          recaptchaSiteKey: ${{ secrets.RECAPTCHA_SITE_KEY }}
          recaptchaSecretKey: ${{ secrets.RECAPTCHA_SECRET_KEY }}
        run: |
          envsubst < my-house24-admin/src/main/resources/application_template.yml > my-house24-admin/src/main/resources/application.yml
          cat my-house24-admin/src/main/resources/application.yml
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build with Maven
        run: ./mvnw clean ; ./mvnw package -Dmaven.test.skip spring-boot:build-image
      - name: Tag and push admin image
        run: docker tag my-house24-admin ${{ secrets.DOCKERHUB_USERNAME }}/my-house24-admin
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-house24-admin