name: Build and push cabinet image and restart container

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'my-house24-cabinet/**'

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_ROOT_PASSWORD}}
          MYSQL_DATABASE: my_house24
          MYSQL_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Add secret
        env:
          awsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sendgridSecretKey: ${{ secrets.SENDGRID_SECRET_KEY }}
          sendgridSender: ${{ secrets.SENDGRID_SENDER }}
          recaptchaSiteKey: ${{ secrets.RECAPTCHA_SITE_KEY }}
          recaptchaSecretKey: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          databasePassword: ${{secrets.DATABASE_PASSWORD}}
        run: |
          envsubst < my-house24-cabinet/src/main/resources/application_template.yml > my-house24-cabinet/src/main/resources/application.yml
          cat my-house24-cabinet/src/main/resources/application.yml

      - name: Run tests
        run: cd my-house24-cabinet && mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: my-house24-cabinet/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-house24-cabinet:latest

      - name: Restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Restarting container"
            docker stop my-house24-Rudiuk_Lesyk-cabinet
            docker rm my-house24-Rudiuk_Lesyk-cabinet
            docker image rm ruduknasta13074/my-house24-cabinet
            docker run -d -p 7081:8080 --name my-house24-Rudiuk_Lesyk-cabinet --net my-house24-Rudiuk_Lesyk-network -e MYSQL_HOST=my-house24-Rudiuk_Lesyk-db -e MYSQL_USER=root -e MYSQL_PASSWORD=${{ secrets.DATABASE_PASSWORD }} ruduknasta13074/my-house24-cabinet
            echo "Container has been updated"          
            exit