name: Notification
on:
  push:
    branches:
      - master
      - main
      - dev
jobs:

  build:
    name: Notification on push
    runs-on: ubuntu-latest
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHANNEL_NAME }}
          token: ${{ secrets.TG_CHANNEL_TOKEN }}